// Posts //
export const GET_POSTS = 'GET_POSTS'
export const ADD_POST = 'ADD_POST'
export const DELETE_POST = 'DELETE_POST'
export const SET_CURRENT_POST = 'SET_CURRENT_POST'
export const CLEAR_CURRENT_POST = 'CLEAR_CURRENT_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const FILTER_POSTS = 'FILTER_POSTS'
export const CLEAR_POSTS = 'CLEAR_POSTS'
export const CLEAR_FILTER_POST = 'CLEAR_FILTER_POST'
export const POST_ERROR = 'POST_ERROR'
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
// Events //
export const GET_EVENTS = 'GET_EVENTS'
export const ADD_EVENT = 'ADD_EVENT'
export const DELETE_EVENT = 'DELETE_EVENT'
export const SET_CURRENT_EVENT = 'SET_CURRENT_EVENT'
export const CLEAR_CURRENT_EVENT = 'CLEAR_CURRENT_EVENT'
export const UPDATE_EVENT = 'UPDATE_EVENT'
export const FILTER_EVENTS = 'FILTER_EVENTS'
export const CLEAR_EVENTS = 'CLEAR_EVENTS'
export const CLEAR_FILTER_EVENT = 'CLEAR_FILTER_EVENT'
export const EVENT_ERROR = 'EVENT_ERROR'
// export const SET_ALERT = 'SET_ALERT'
// export const REMOVE_ALERT = 'REMOVE_ALERT'
// Auth //
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
//
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

